matrix:
  include:
    - env: NAME=Xcode DESTINATION="platform=iOS Simulator,name=iPhone 8"
      os: osx
      osx_image: xcode9.3
      language: objective-c
      before_script: 
        - pod lib lint --allow-warnings
    - env: NAME=SPM
      script:
        - swift --version
        - swift build
        - swift test
      sudo: required
      dist: trusty
      language: generic
      install:
        - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
script:
- |
  if [ "$NAME" = "Xcode" ]
  then
    xcodebuild test -project RFC3339DateFormatter.xcodeproj -scheme RFC3339DateFormatter -destination "${DESTINATION}" 
  else
    swift test 
  fi
